#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jaxb-v2
Version  : 2.2.10
Release  : 5
URL      : https://github.com/javaee/jaxb-v2/archive/jaxb-2_2_10.tar.gz
Source0  : https://github.com/javaee/jaxb-v2/archive/jaxb-2_2_10.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/com/sun/xml/bind/jaxb-bom-ext/2.3.1/jaxb-bom-ext-2.3.1.pom
Source2  : https://repo.gradle.org/gradle/libs-releases/com/sun/xml/bind/mvn/jaxb-bundles/2.3.1/jaxb-bundles-2.3.1.pom
Source3  : https://repo.gradle.org/gradle/libs-releases/com/sun/xml/bind/mvn/jaxb-parent/2.3.1/jaxb-parent-2.3.1.pom
Source4  : https://repo.gradle.org/gradle/libs-releases/org/glassfish/jaxb/jaxb-bom/2.3.1/jaxb-bom-2.3.1.pom
Source5  : https://repo1.maven.org/maven2/com/sun/xml/bind/mvn/jaxb-bundles/2.2.11/jaxb-bundles-2.2.11.pom
Source6  : https://repo1.maven.org/maven2/com/sun/xml/bind/mvn/jaxb-parent/2.2.11/jaxb-parent-2.2.11.pom
Source7  : https://repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-bom/2.2.11/jaxb-bom-2.2.11.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-1.1 Apache-2.0 BSD-3-Clause CDDL-1.1 GPL-2.0 MIT
Requires: mvn-jaxb-v2-data = %{version}-%{release}
Requires: mvn-jaxb-v2-license = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
### Licensing and Governance
JAXB is licensed under a dual license - CDDL 1.1 and GPL 2.0 with Class-path Exception.
That means you can choose which one of the two suits your needs better and use it under those terms.

%package data
Summary: data components for the mvn-jaxb-v2 package.
Group: Data

%description data
data components for the mvn-jaxb-v2 package.


%package license
Summary: license components for the mvn-jaxb-v2 package.
Group: Default

%description license
license components for the mvn-jaxb-v2 package.


%prep
%setup -q -n jaxb-v2-jaxb-2_2_10

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jaxb-v2
cp jaxb-ri/License.html %{buildroot}/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_License.html
cp jaxb-ri/License.txt %{buildroot}/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_License.txt
cp jaxb-ri/bundles/ri/src/main/resources/License.txt %{buildroot}/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_bundles_ri_src_main_resources_License.txt
cp jaxb-ri/docs/release-documentation/src/main/resources/ThirdPartyLicense.txt %{buildroot}/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_docs_release-documentation_src_main_resources_ThirdPartyLicense.txt
cp jaxb-ri/docs/release-documentation/src/main/resources/license.txt %{buildroot}/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_docs_release-documentation_src_main_resources_license.txt
cp jaxb-ri/external/rngom/src/main/resources/META-INF/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_external_rngom_src_main_resources_META-INF_LICENSE.txt
cp jaxb-ri/licenceheader.txt %{buildroot}/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_licenceheader.txt
cp jaxb-ri/tools/apgen/src/com/sun/tools/LicenceCodeWriter.java %{buildroot}/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_tools_apgen_src_com_sun_tools_LicenceCodeWriter.java
cp jaxb-ri/tools/apgen/src/com/sun/tools/LicenceTask.java %{buildroot}/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_tools_apgen_src_com_sun_tools_LicenceTask.java
cp jaxb-ri/tools/config/copyright.txt %{buildroot}/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_tools_config_copyright.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-bom-ext/2.3.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-bom-ext/2.3.1/jaxb-bom-ext-2.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/mvn/jaxb-bundles/2.3.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/mvn/jaxb-bundles/2.3.1/jaxb-bundles-2.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/mvn/jaxb-parent/2.3.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/mvn/jaxb-parent/2.3.1/jaxb-parent-2.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jaxb/jaxb-bom/2.3.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jaxb/jaxb-bom/2.3.1/jaxb-bom-2.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/mvn/jaxb-bundles/2.2.11
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/mvn/jaxb-bundles/2.2.11/jaxb-bundles-2.2.11.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/mvn/jaxb-parent/2.2.11
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/mvn/jaxb-parent/2.2.11/jaxb-parent-2.2.11.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jaxb/jaxb-bom/2.2.11
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jaxb/jaxb-bom/2.2.11/jaxb-bom-2.2.11.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-bom-ext/2.3.1/jaxb-bom-ext-2.3.1.pom
/usr/share/java/.m2/repository/com/sun/xml/bind/mvn/jaxb-bundles/2.2.11/jaxb-bundles-2.2.11.pom
/usr/share/java/.m2/repository/com/sun/xml/bind/mvn/jaxb-bundles/2.3.1/jaxb-bundles-2.3.1.pom
/usr/share/java/.m2/repository/com/sun/xml/bind/mvn/jaxb-parent/2.2.11/jaxb-parent-2.2.11.pom
/usr/share/java/.m2/repository/com/sun/xml/bind/mvn/jaxb-parent/2.3.1/jaxb-parent-2.3.1.pom
/usr/share/java/.m2/repository/org/glassfish/jaxb/jaxb-bom/2.2.11/jaxb-bom-2.2.11.pom
/usr/share/java/.m2/repository/org/glassfish/jaxb/jaxb-bom/2.3.1/jaxb-bom-2.3.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_License.html
/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_License.txt
/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_bundles_ri_src_main_resources_License.txt
/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_docs_release-documentation_src_main_resources_ThirdPartyLicense.txt
/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_docs_release-documentation_src_main_resources_license.txt
/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_external_rngom_src_main_resources_META-INF_LICENSE.txt
/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_licenceheader.txt
/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_tools_apgen_src_com_sun_tools_LicenceCodeWriter.java
/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_tools_apgen_src_com_sun_tools_LicenceTask.java
/usr/share/package-licenses/mvn-jaxb-v2/jaxb-ri_tools_config_copyright.txt
